exclude = [
  "^https://github.com/tinyland-inc/tummycrypt/compare",
  "^https://nix-cache.fuzzy-dev.tinyland.dev",
  "localhost",
  "127\\.0\\.0\\.1",
  "192\\.168\\.",
  "dees-appu-bearts",
  "seaweedfs.tcfs.svc",
]
include_fragments = true
max_concurrency = 8
timeout = 30
