---
tummy_access_key_kate: uebx7j7nbScZE4LwqdcHwy7SnqnyRLK3QQxc3NAySDoZjsib5f9RK
tummy_secret_key_kate: vCi9xPykb9P52FxNsssawYc5CLdTfx4ACqdbFXdUeHWSRyzKLXHum
tummy_rclone_password1: c93YrceAC27qjZiKJnAH4xCFabJAbX7TvQYa4cjpdbL9hrAfy5ngu4AX7x5vdkA
tummy_rclone_password2: SmZMqWu2g2SsEY2nnT7vnqypsVavixnoEdA24KR3EsNWZZ5MnnXY7jP4CAyN7jZ
uname: kate