global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: tcfsd
    static_configs:
      - targets: ['host.docker.internal:9100']
    relabel_configs:
      - target_label: job
        replacement: tcfsd

  - job_name: nats
    static_configs:
      - targets: ['nats:8222']

  - job_name: seaweedfs
    static_configs:
      - targets:
          - 'seaweed-master-1:9333'
          - 'seaweed-filer:8888'
